/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dragonsSol from "./Dragons.sol";
export type { dragonsSol };
import type * as dragonsV2Sol from "./DragonsV2.sol";
export type { dragonsV2Sol };
import type * as weaponBurnSol from "./WeaponBurn.sol";
export type { weaponBurnSol };
export type { ERC1155Factory } from "./ERC1155Factory";
export type { Lock } from "./Lock";
export type { MoonrunnersLoot } from "./MoonrunnersLoot";
export type { Trophies } from "./Trophies";
