/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILoot,
  ILootInterface,
} from "../../../contracts/WeaponBurn.sol/ILoot";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "controlledBurn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILoot__factory {
  static readonly abi = _abi;
  static createInterface(): ILootInterface {
    return new utils.Interface(_abi) as ILootInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILoot {
    return new Contract(address, _abi, signerOrProvider) as ILoot;
  }
}
