/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILoot__factory } from "./ILoot__factory";
export { WeaponBurn__factory } from "./WeaponBurn__factory";
