/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DragonsV2 } from "./DragonsV2";
export type { ILoot } from "./ILoot";
export type { ITrophies } from "./ITrophies";
