/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dragons } from "./Dragons";
export type { ILoot } from "./ILoot";
export type { ITrophies } from "./ITrophies";
