/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dragonsSol from "./Dragons.sol";
export * as dragonsV2Sol from "./DragonsV2.sol";
export * as weaponBurnSol from "./WeaponBurn.sol";
export { ERC1155Factory__factory } from "./ERC1155Factory__factory";
export { Lock__factory } from "./Lock__factory";
export { MoonrunnersLoot__factory } from "./MoonrunnersLoot__factory";
export { Trophies__factory } from "./Trophies__factory";
