/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Dragons__factory } from "./Dragons__factory";
export { ILoot__factory } from "./ILoot__factory";
export { ITrophies__factory } from "./ITrophies__factory";
